# -*- coding: utf-8 -*-
"""relatorio_vendas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xw6G4ws5Q06ItQEgC4Poyj_cOUOt8EwR

<img alt="Colaboratory logo" width="15%" src="https://raw.githubusercontent.com/carlosfab/escola-data-science/master/img/novo_logo_bg_claro.png">

#### **Python do Zero**
*by [sigmoidal.ai](https://sigmoidal.ai)*

---

## Relatórios da Empresa

Agora que temos as ferramentas e o conhecimento para usá-las, é hora de botar a mão na massa, e botar todo o poder de tudo que aprendemos pra funcionar na prática.


<center><img width="50%" src="https://image.freepik.com/free-photo/workplace-results-professional-report-accounting-during_1418-61.jpg"></center>

Em nossa jornada rumo à automação de tarefas repetitivas em nossa rotina de trabalho, vamos aprender a extrair e utilizar informações úteis de nossos documentos.

Mais uma vez utilizando a biblioteca [PDF Plumber](https://github.com/jsvine/pdfplumber) vamos extrair e manipular informações de diversos relatórios em pdf ao mesmo tempo.

Para isso, vamos precisar fazer o download dos arquivos de apoio que foram disponibilizados como material complementar dessa aula. 

Lembrando: Nativamente, o Google Colab não possui essa biblioteca instalada, então nós precisamos instalar a mesma no nosso ambiente.

Para isso, vamos utilizar o gerenciador de pacotes `pip`, e com o comando `install` vamos instalar a biblioteca.

###Projeto do curso Python do Zero - Sigmoidal
"""

# instalando o pdf plumber
!pip install pdfplumber -q

# montando o drive
from google.colab import drive
drive.mount('/content/drive')

# importando pacotes necessários
import pdfplumber
import os

# mudar para diretório com pdfs da semana
os.chdir('/content/drive/MyDrive/DataScience/Sigmoidal/PDZ/relatorios')

# checar se estou no diretório correto
os.getcwd()

# imprimir lista com arquivos no diretório
arquivos_semana = os.listdir()
print(arquivos_semana)

# abrir relatório de exemplo
relatorio = pdfplumber.open('/content/drive/MyDrive/DataScience/Sigmoidal/PDZ/relatorios/20200801.pdf')

# abrir a primeira página do relatório
p1 = relatorio.pages[0]

# extrair o texto da primeira página do primeiro relatório
texto = p1.extract_text()
print(texto)

# visualizando como o chega o texto
texto

# dividindo o texto por linhas
texto.split('\n')

# retirando tabulações
texto.split('\n')[6].replace('\t', '')

# retirando o R$
texto.split('\n')[6].replace('\t', '').split("R$")

# valor ainda é string
texto.split('\n')[6].replace('\t', '').split("R$")[1]

# transformando em float
float(texto.split('\n')[6].replace('\t', '').split("R$")[1])

# criando um contador
soma = 0

# criando a função
for arquivo in arquivos_semana:
  relatorio = pdfplumber.open(arquivo)
  pagina = relatorio.pages[0]
  texto = pagina.extract_text()
  valor = texto.split('\n')[6].replace('\t', '').split("R$")[1]
  valor = float(valor)
  soma = soma + valor
  print(arquivo, '---->', valor)

# soma dos relatórios
print('Receita dos últimos 5 dias: R$', soma)